# Parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.25  # layer channel multiple
activation_type: silu
max_channels: 1024

anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32


# YOLOv8.0n backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 3, 2]],  # 0-P1/2
    [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
    [-1, 3, C2f, [128, True]],
    [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
    [-1, 6, C2f, [256, True]],
    [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
    [-1, 6, C2f, [512, True]],
    [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
    [-1, 3, C2f, [1024, True]],
    [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv8.0n head
head:
  [[-1, 1, nn.Upsample, [None, 2, 'nearest']],
    [[-1, 6], 1, Concat, [1]],  # cat backbone P4
    [-1, 3, C2f, [512]],  # 12

    [-1, 1, nn.Upsample, [None, 2, 'nearest']],
    [[-1, 4], 1, Concat, [1]],  # cat backbone P3
    [-1, 3, C2f, [256]],  # 15 (P3/8-small)

    [-1, 1, Conv, [256, 3, 2]],
    [[-1, 12], 1, Concat, [1]],  # cat head P4
    [-1, 3, C2f, [512]],  # 18 (P4/16-medium)

    [-1, 1, Conv, [512, 3, 2]],
    [[-1, 9], 1, Concat, [1]],  # cat head P5
    [-1, 3, C2f, [1024]],  # 21 (P5/32-large)

    [[15, 18, 21], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]